server:
  port: 8083
spring:
  datasource:
    password: 88888888
    username: root
    url: jdbc:mysql://localhost:3306/service-passenger-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-passenger-user
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.218.99:8848

