server:
  port: 8081
spring:
  application:
    name: api-passenger
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.218.99:8848
  redis:
    host: 124.221.218.99
    port: 6379
    database: 1
    password: 123456